### PR TITLE
linux: Capture engine

### PR DESCRIPTION
**Pull request by MAlba124**
Linux support as discussed in #6 .

### CODE REVIEW

**Comment by clearlysid** [comment]
Thanks for the great PR, I'll test and review this within this week.

@MAlba124: do you know if this will be okay to test within WSL? I don't have a dedicated Linux machine on me at the moment.

**Comment by MAlba124** [comment]
Hello @clearlysid.

I'm not sure if it will run in WSL. It requires that a `xdg-desktop-portal` implementation in running AND supporting the `ScreenCast` portal (which requires pipewire run). If you get a full desktop environment running, you would probably be able to test.

I have tested this on a fresh install of ubuntu-22.04 in a VM with these packages installed:
```console
sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream'
sudo apt install pipewire build-essential pkg-config libasound2-dev \
	libavcodec-dev libavformat-dev libswscale-dev libpipewire-0.3-dev \
	libclang-dev
```

I have also tested on NixOS using `sway`+`xdg-desktop-portal-wlr`.

**Comment by clearlysid** [comment]
@MAlba124 so sorry about the delay. We've made some big changes to the base branch, hence the merge conflicts.

If you can spare the time to re-look this, we'd absolutely be grateful! But if not don't worry, I'll take a look at this as soon as I get access to a Linux machine (later this week) and help out with the changes 🫡

**Comment by ZohebMOPO** [comment]
@MAlba124 There is some libspa-sys error thrown by rust when I am building, I couldn't find any pre-requisites in the documentation of libspa-sys crate. Also the rustix crate is expecting rust-nightly. Below is my system info also if that helps.

https://github.com/clearlysid/scap/assets/72716462/be5061b2-0588-48fe-b688-ec1bd4294135

image

**Comment by MAlba124** [comment]
Hello @ZohebMOPO.
The `pipewire-rs` crate does indeed fail to build when using older versions of `libspa` as highlighted in [this issue](https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/issues/75). On Ubuntu I had to use a the debian pipewire ppa (ppa:pipewire-debian/pipewire-upstream) to get it working. This will also be available on elementaryOS?

About the nightly requirement, I'm able to build and run using stable.

**Comment by clearlysid** [comment]
@MAlba124 is there a way to use FFmpeg-based capturing instead? Our end goal is to have scap as a foundation to make other distributable app, so we might run into future issues with mismatching pipewire setups etc.

Or have I understood this wrong and pipewire simply compiles into a binary and to be bundled with scap?

**Comment by clearlysid** [comment]
@ZohebMOPO your Rust version might be out of date, I was able to build this using Rust v1.75.0 (latest stable, non-nightly)

**Comment by clearlysid** [comment]
@MAlba124 thanks for the PR, this works exactly as intended on my test-bench running Debian 12! 🔥

I'm just looking to understand pipewire slightly better, and will merge this as soon as I make some progress there.

**Comment by MAlba124** [comment]
@clearlysid So pipewire is an audio and video server and framework in the same category as pulseaudi, and it's currently a requirement for screencasting in a cross DE/WM Wayland/X11 way using xdg-desktop-portal.
I could try and implement a solution using FFmpeg and xcb, but this would only work for X11.

**Comment by clearlysid** [comment]
Thanks, understood. Also spent some time tinkering with it and seems like we'll have a much easier time supporting a wider variety of distros/linux setups in general with Pipewire instead of any other so I feel like this is the right approach too.

Proceeding with merging now ✅

**Comment by Pranav2612000** [comment]
@allcontributors please add @MAlba124 for code

**Pull request merged**
